# Generated by Django 4.1.5 on 2023-01-14 19:28

import json, os

from django.conf import settings
from django.db import migrations


def import_fruits(apps, schema_editor):
    # get the correct versions of models using the app registry
    Fruit = apps.get_model("example_app", "Fruit")

    with open(os.path.join(settings.BASE_DIR, 'example_app', 'static', 'json_samples', 'fruits.json')) as file:
        data = json.load(file)
    
    fruits = [Fruit(data=fruit) for fruit in data]
    Fruit.objects.bulk_create(fruits)


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_fruits),
    ]
